### ISSUE TITLE
Output table not been rendered in GitHub pages

### ISSUE THREAD

**Issue by arthurbdiniz** [Dirrk/terraform-docs#20]
Hi everyone, recently I notice that when using the `tf_docs_output_method: inject` mode into `README.md` the **Output table** breaks using **GitHub Pages.**

Version: **terraform-docs@v1.0.7**
## Workflow
```yml
- name: Render terraform docs inside the README.md and push changes back to pushed branch
      uses: Dirrk/terraform-docs@v1.0.7
      with:
        tf_docs_working_dir: .
        tf_docs_output_file: README.md
        tf_docs_output_method: inject
        tf_docs_git_push: 'true'
        tf_docs_git_commit_message: 'terraform-docs: automated update action'
```
## Generated README
In the example above we can see that the **output table** in **README.md** is been correct rendered while in **GitHub Pages** broken. 
- [README.md](https://github.com/DNXLabs/terraform-aws-ecs/blob/master/README.md#outputs)
- [GitHub Pages](https://dnxlabs.github.io/terraform-aws-ecs/#outputs)

## Possible solution
Taking a look at the **README.md** I did some tests and I notice that when a **new line** are added to the top of `<!-- END_TF_DOCS -->` this issue goes away.

#### Before
```markdown
## Outputs

| Name | Description |
|------|-------------|
| cidr\_block | CIDR for VPC created |
| db\_subnet\_group\_id | n/a |
| internet\_gateway\_id | ID of Internet Gateway created |
| nat\_gateway\_ids | List of NAT Gateway IDs |
| private\_subnet\_cidrs | List of private subnet CIDRs |
| private\_subnet\_ids | List of private subnet IDs |
| public\_subnet\_cidrs | List of public subnet CIDRs |
| public\_subnet\_ids | List of public subnet IDs |
| secure\_subnet\_cidrs | List of secure subnet CIDRs |
| secure\_subnet\_ids | List of secure subnet IDs |
| vpc\_id | ID for VPC created |
<!-- END_TF_DOCS -->
```

#### After
```markdown
## Outputs

| Name | Description |
|------|-------------|
| cidr\_block | CIDR for VPC created |
| db\_subnet\_group\_id | n/a |
| internet\_gateway\_id | ID of Internet Gateway created |
| nat\_gateway\_ids | List of NAT Gateway IDs |
| private\_subnet\_cidrs | List of private subnet CIDRs |
| private\_subnet\_ids | List of private subnet IDs |
| public\_subnet\_cidrs | List of public subnet CIDRs |
| public\_subnet\_ids | List of public subnet IDs |
| secure\_subnet\_cidrs | List of secure subnet CIDRs |
| secure\_subnet\_ids | List of secure subnet IDs |
| vpc\_id | ID for VPC created |

<!-- END_TF_DOCS -->
```

## Conclusion
In order to fix this bug to everyone using this action, a **new line** could be added when the temporary file, `tf_doc.md`, are generated or added inside the `sed` command that joins this temporary file within the output file.

`terraform-docs/src/common.sh:68`
```bash
sed -i -ne '/<!--- BEGIN_TF_DOCS --->/ {p; r /tmp/tf_doc.md' -e ':a; n; /<!--- END_TF_DOCS --->/ {p; b}; ba}; p' "${WORKING_DIR}/${INPUT_TF_DOCS_OUTPUT_FILE}"
```
I`m not a good bash scripter so it would be good to have opinions about which option is the best for this or is there any other solutions?
