### ISSUE TITLE
injection resetting other actions status

### ISSUE THREAD

**Issue by daroga0002** [Dirrk/terraform-docs#23]
Probably this is not related directly to this, but I have issue that when I use this action and have second workflow  action `inject` action from terraform-docs resets all statuses from other actions and what is more it is finishing that on my branch there is no other actions triggered:
![image](https://user-images.githubusercontent.com/20227477/83245015-794ab580-a1a0-11ea-801f-414ae115c46e.png)

**Comment by Dirrk** [comment]
@daroga0002 what does your action.yml look like?

**Comment by daroga0002** [comment]
I am using this workflow file `terraform-docs.yml`:
```
name: Generate terraform docs
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  docs:
    runs-on: self-hosted
    steps:
    - run: sudo chown -R `id -u`:`id -g` ./
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs inside the USAGE.md and push changes back to PR branch
      uses: Dirrk/terraform-docs@v1.0.7
      with:
        tf_docs_content_type: table
        tf_docs_find_dir: .
        tf_docs_output_file: USAGE.md
        tf_docs_output_method: inject
        tf_docs_git_push: 'true'
        tf_docs_git_commit_message: "terraform-docs: generated by github action"
```

and having second `terraform.yml` which is doing terraform plan. So when documentation will inject docs to branch it resets all Github checks and doesnt trigger again `terrafrom.yml`  to make plan. This is causing that required check on branch is not invoked at all.
